# /-----------------------------------------------------------------------------/
# /-----------------------------------------------------------------------------/

# Прод среда
production:

  # Настройки телеграмм
  bot_token: "YOUR_BOT_TOKEN_HERE"

  # Настройки почтового ящика
  mail:
    address: "Bot@yourdomain.ru"
    password: "YOUR_EMAIL_PASSWORD_HERE"
    smtp_server: "mail.nic.ru"
    smtp_port: 587
    use_tls: false  # false для порта 587 (STARTTLS), true для порта 465 (SMTPS)
    timeout: 30    # таймаут в секундах

  # Настройки Битрикс24
  bitrix24:
    webhook: "YOUR_BITRIX24_WEBHOOK_URL_HERE"
    guarantee_mp_category_id: 3

  # Настройки БД
  postgres:
    host: localhost
    port: 5433
    user: your_db_user
    password: "YOUR_DB_PASSWORD_HERE"
    database: your_db_name


# Среда разработки
development:

  # Настройки телеграмм
  bot_token: "YOUR_BOT_TOKEN_HERE"

  # Настройки почтового ящика
  mail:
    address: "Bot@yourdomain.ru"
    password: "YOUR_EMAIL_PASSWORD_HERE"
    smtp_server: "mail.nic.ru"
    smtp_port: 587
    use_tls: false  # false для порта 587 (STARTTLS), true для порта 465 (SMTPS)
    timeout: 30    # таймаут в секундах

  # Настройки Битрикс24
  bitrix24:
    webhook: "YOUR_BITRIX24_WEBHOOK_URL_HERE"
    guarantee_mp_category_id: 3

  # Настройки БД
  postgres:
    host: localhost
    port: 5433
    user: your_db_user
    password: "YOUR_DB_PASSWORD_HERE"
    database: your_db_name
